To-Do-List
MbathaSimphiwe/TO-DO-LIST pull request #1
Opened 2024-11-08 09:54 UTC by 217033Mbatha

2024-11-08 09:57 UTC, ClementRep approved these changes

2024-11-13 11:18 UTC, Valerietshuma requested changes

2024-11-13 11:18 UTC, Valerietshuma commented on public/style.css
> +}
Your project so far it is appealing but I have noticed that the added item boxes are not aligned with the add task box, I f you can try and center your items that would enhance the appearance of your project

2024-11-14 07:49 UTC, MulamuMammba approved these changes

2024-11-14 07:50 UTC, Valerietshuma approved these changes

2024-11-14 07:50 UTC, merged